### PR TITLE
[WIP] Data augmentation

### PR DESCRIPTION
**Pull request by godardt**
This PR adds data augmentation to the trained images

### CODE REVIEW

**Comment by godardt** [comment]
@jamesrequa I let you finish the work from here :)

**Comment by godardt** [comment]
[Data augmentation](https://trello.com/c/5K9DSnlZ/7-data-augmentation)

**Comment by EKami** [comment]
@jamesrequa I think we can rename this PR to "Remove opencv", remove the trello card assignation and merge the changes for now. We can come back to this card later. I don't like having pending changes on jupyter notebooks because merging is horrible :( . Wdyt?

**Review by jamesrequa — APPROVED** [review]
Looks good!

**Pull request merged**
